import { join, basename } from "path";
import { mkdir, writeFile, stat, readFile } from "node:fs/promises";
import { log, colors } from "../utils";
import { i18n } from "../i18n";
import { memory } from "../memory";

export type WorkflowType = "specify" | "plan" | "validate" | "reverse";

function getTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

/**
 * Read workflow template from .litespec/workflows/
 * Falls back to source directory (for development/tests where .litespec/ doesn't exist).
 */
async function getWorkflowTemplate(type: WorkflowType, locale: string): Promise<string> {
  const root = process.cwd();
  const templateDir = join(root, ".litespec", "workflows");
  const lang = locale === "zh" ? "zh" : "en";

  // Try user's .litespec/workflows/ first (flat structure, no language subdir)
  const templatePath = join(templateDir, `${type}.md`);
  try {
    return await readFile(templatePath, "utf-8");
  } catch {
    // Fallback: read from source directory (development mode, has language subdirs)
    const sourcePath = join(import.meta.dir, "..", "workflows", lang, `${type}.md`);
    try {
      return await readFile(sourcePath, "utf-8");
    } catch {
      // Final fallback: return a basic template
      return `# ${type.charAt(0).toUpperCase() + type.slice(1)}

<!-- Generated by LiteSpec -->
`;
    }
  }
}

export async function runWorkflow(type: WorkflowType, args: string[]) {
  const t = i18n.t;
  const root = process.cwd();
  const docsDir = join(root, "docs", "litespec");

  await mkdir(docsDir, { recursive: true });

  let name = args[0];
  if (!name) {
    name = `${getTimestamp()}-${type}`;
  }

  // Prevent path traversal
  if (name !== basename(name) || name.includes("..")) {
    log(colors.red, "Error: Invalid name. Name must not contain path separators or '..'.");
    return;
  }

  const filePath = join(docsDir, `${name}.md`);

  try {
    await stat(filePath);
    log(colors.yellow, `${t.workflows.fileExists} ${filePath}`);
    return;
  } catch {}

  // Read template from .litespec/workflows/
  const locale = i18n.currentLocale || "en";
  const content = await getWorkflowTemplate(type, locale);

  await writeFile(filePath, content);
  log(colors.green, `${t.workflows.created} ${filePath}`);
  log(colors.gray, t.workflows.nextStep);

  // Record to memory
  await memory.recordWorkflow(type, `${name}.md`);
}
