import { Adapter } from "./registry";
export const claudeAdapter: Adapter = {
  name: "Claude Code",
  configPath: "CLAUDE.md",
  contentTemplate: "# Claude Code Instructions\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
