import { Adapter } from "./registry";
export const codebuddyAdapter: Adapter = {
  name: "CodeBuddy",
  configPath: ".codebuddy/rules.md",
  contentTemplate: "# CodeBuddy Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
