import { Adapter } from "./registry";
export const cursorAdapter: Adapter = {
  name: "Cursor",
  configPath: ".cursorrules",
  contentTemplate: "# Cursor Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
