import { Adapter } from "./registry";
export const qoderCnAdapter: Adapter = {
  name: "Qoder CN",
  configPath: ".lingma/rules/litespec.md",
  contentTemplate: "---\ntrigger: always_on\n---\n# LiteSpec Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
