import { Adapter } from "./registry";
export const qoderAdapter: Adapter = {
  name: "Qoder",
  configPath: ".qoderrules",
  contentTemplate: "# Qoder Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
