import { Adapter } from "./registry";
export const traeAdapter: Adapter = {
  name: "Trae",
  configPath: ".trae/rules",
  contentTemplate: "# Trae Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
