import { Adapter } from "./registry";
export const workbuddyAdapter: Adapter = {
  name: "WorkBuddy",
  configPath: ".workbuddy/rules.md",
  contentTemplate: "# WorkBuddy Rules\n\nThis file is auto-generated by LiteSpec. Do not edit manually.\n\n",
};
